### ISSUE TITLE
safeguards validate error: Cannot resolve serverless.yml: "provider.stage" property is not accessible

### ISSUE THREAD

**Issue by zachwhaley** [serverless/safeguards-plugin#27]
Trying to run `safeguards validate` I am hit with this error

```shell
→ npx sls safeguards validate -s staging --policy-file safeguards-policy.yaml

 Serverless Error ----------------------------------------

  Cannot resolve serverless.yml: "provider.stage" property is not accessible (configured behind variables which cannot be resolved at this stage)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.17.0
     Framework Version:         2.43.1 (local)
     Plugin Version:            5.1.3
     SDK Version:               4.2.2
     Components Version:        3.10.1
```

Relevant bits of my `serverless.yml`

```yaml
service: foo

frameworkVersion: '2'
variablesResolutionMode: 20210326
configValidationMode: off
useDotenv: true

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

  stage: ${opt:stage, env:FOO_STAGE, 'rnd'}
  region: ${opt:region, env:AWS_DEFAULT_REGION, 'us-east-1'}

  deploymentBucket:
    blockPublicAccess: true
    serverSideEncryption: aws:kms
    sseKMSKeyId: ${ssm:serverless_kms_key, null}
  vpc:
    securityGroupIds: ${ssm:/application/vpc_security_groups, null}
    subnetIds: ${ssm:/application/vpc_subnets, null}
  apiGateway:
    restApiId: ${ssm:/apigateway/id, null}
    restApiRootResourceId: ${ssm:/apigateway/root_resource_id, null}
  iam:
    role: !Sub arn:aws:iam::${AWS::AccountId}:role/FooRole
  kmsKeyArn: ${ssm:lambda_kms_key, null}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
          authorizer: ${self:custom.apiGatewayAuthorizer.${sls:stage}, null}

custom:
  apiGatewayAuthorizer:
    staging:
      type: ${ssm:/apigateway/authorizer_type, null}
      authorizerId: ${ssm:/apigateway/authorizer_id, null}

plugins:
  - '@serverless/safeguards-plugin'
  - others...
```
